<fieldset>
    <legend><?php echo $this->translate('Local Contexts Content'); ?></legend>
    <div class="field">
        <div class="field-meta">
            <label for="o:lc-content"><?php echo $this->translate('Local Contexts property'); ?></label>
            <a href="#" class="expand" aria-expanded="false" aria-controls="lc-property-description" aria-label="<?php echo $this->translate("Expand"); ?>"></a>
            <div class="collapsible" id="lc-property-description">
                <div class="field-description"><?php echo $this->translate('Assign Local Contexts content to chosen metadata field.'); ?></div>
            </div>
        </div>
        <div class="inputs localcontexts">
            <?php
            echo $this->propertySelect([
                'name' => 'o:lc-content-property',
                'attributes' => [
                    'class' => 'chosen-select',
                    'multiple' => false,
                    'data-placeholder' => 'Select a property', // @translate
                ],
            ]);
            ?>
        </div>
    </div>
    <div class="field">
        <div class="field-meta">
            <label for="lc_language"><?php echo $this->translate('Local Contexts language'); ?></label>
            <a href="#" class="expand" aria-expanded="false" aria-controls="lc-language-description" aria-label="<?php echo $this->translate("Expand"); ?>"></a>
            <div class="collapsible" id="lc-language-description">
                <div class="field-description"><?php echo $this->translate('Only display content in selected language (Note: must already be generated and retrieved from LC Hub).'); ?></div>
            </div>
        </div>
        <div class="inputs localcontexts"><?php echo $this->formSelect($language_select); ?></div>
    </div>
    <div class="field">
        <div class="field-meta">
            <label for="o:lc-content"><?php echo $this->translate('Local Contexts content'); ?></label>
            <a href="#" class="expand" aria-expanded="false" aria-controls="lc-notices-description" aria-label="<?php echo $this->translate("Expand"); ?>"></a>
            <div class="collapsible" id="lc-notices-description">
                <div class="field-description"><?php echo $this->translate('Local Contexts value(s) to apply to above field.'); ?></div>
            </div>
        </div>
        <div class="inputs">
            <?php foreach ($this->lc_content as $project): ?>
            <label class="local-contexts-multicheckbox">
                <div class="column check">
                <input type='checkbox' class="column check" name='o:lc-content[]' aria-labelledby="lc-notice-title-<?php echo $this->escapeHtml($project['project_key']); ?>" value='<?php echo $this->escapeHtml($project['value']); ?>'>
                </div>
                <div class="column content">
                <?php echo $project['label']; ?>
                </div>
            </label>
            <?php endforeach; ?>
        </div>
    </div>
</fieldset>