<fieldset>
    <legend><?php echo $this->translate('Local Contexts Notices'); ?></legend>
    <div class="field">
        <div class="field-meta">
            <label for="o:lc-content"><?php echo $this->translate('Property'); ?></label>
            <a href="#" class="expand" aria-label="<?php echo $this->translate("Expand"); ?>"></a>
            <div class="collapsible">
                <div class="field-description"><?php echo $this->translate('Assign Local Contexts notice(s) as chosen metadata field.'); ?></div>
            </div>
        </div>
        <div class="inputs localcontexts">
            <?php
            echo $this->propertySelect([
                'name' => 'o:lc-content-property',
                'attributes' => [
                    'class' => 'chosen-select',
                    'multiple' => false,
                    'data-placeholder' => 'Select a property', // @translate
                ],
            ]);
            ?>
        </div>
    </div>
    <div class="field">
        <div class="field-meta">
            <label for="lc_language"><?php echo $this->translate('Local Contexts language'); ?></label>
            <a href="#" class="expand" aria-label="<?php echo $this->translate("Expand"); ?>"></a>
            <div class="collapsible">
                <div class="field-description"><?php echo $this->translate('Assign selected Local Contexts notice(s) to chosen metadata field in chosen language(s).'); ?></div>
            </div>
        </div>
        <div class="inputs localcontexts"><?php echo $this->formSelect($language_select); ?></div>
    </div>
    <div class="field">
        <div class="field-meta">
            <label for="o:lc-content"><?php echo $this->translate('Local Contexts Notices'); ?></label>
            <a href="#" class="expand" aria-label="<?php echo $this->translate("Expand"); ?>"></a>
            <div class="collapsible">
                <div class="field-description"><?php echo $this->translate('Assign Local Contexts notice(s) as chosen metadata field.'); ?></div>
            </div>
        </div>
        <div class="inputs">
            <label class="local-contexts-multicheckbox">
            <?php foreach ($this->lc_content as $project): ?>
                <input type='checkbox' class="column check" name='o:lc-content[]' value='<?php echo $this->escapeHtml(json_encode($project)); ?>'>
                <div class="column content">
                <?php echo $this->partial('local-contexts/common/project.phtml', ['project' => $project]); ?>  
                </div>
            <?php endforeach; ?>
            </label>
        </div>
    </div>
</fieldset>