<div class="field">
    <div class="field-meta">
        <label for="o:lc-content"><?php echo $this->translate('Local Contexts Notices'); ?></label>
        <a href="#" class="expand" aria-label="<?php echo $this->translate("Expand"); ?>"></a>
        <div class="collapsible">
            <div class="field-description"><?php echo $this->translate('Assign Local Contexts notice(s) as Dublin Core Rights metadata.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php
        // $writer = new \Laminas\Log\Writer\Stream('logs/application.log');
        // $logger = new \Laminas\Log\Logger();
        // $logger->addWriter($writer);
        // // $logger->info($data['lc_content_property[property_id]']);
        // $logger->info(print_r($data, 1));
        echo $this->propertySelect([
            'name' => 'o:lc-content-property[o:id]',
            'attributes' => [
                'class' => 'chosen-select',
                'multiple' => false,
                'data-placeholder' => 'Select a property', // @translate
            ],
        ]);
        $html = '';
        foreach ($this->lc_content as $content) {
            $html .= "<div class='column check'><input type='checkbox' name='o:lc-content[]' value='" . $this->escapeHtml(json_encode($content)) . "'></div>";
            $html .= "<img class='column image' src='" . $content['image_url'] . "'>";
            $html .= "<div class='column text'><div class='name'>" . $content['name'];
            if (isset($content['language'])) {
                $html .= "<span class='language'> (" . $content['language'] . ")</span>";
            }
            $html .= "</div>";
            $html .= "<div class='description'>" . $content['text'] . "</div></div>"; 
        } 
        echo $html;
        ?>
    </div>
</div>
