<?php $projectUrl = $notice['project_url']; ?>
<?php if (isset($projectUrl)): ?>
<a href="<?php echo $projectUrl; ?>" class="local-contexts-notice" target="_blank">
<?php else: ?>
<div class="local-contexts-notice">
<?php endif; ?>
        <?php if ($notice['image_url'] !== ''): ?>
        <img class='image' src='<?php echo $notice['image_url']; ?>' alt=''>
        <?php endif; ?>
        <div class='local-context-notice-meta'>
            <div class='notice-name'>
                <?php echo $notice['name']; ?>
                <?php if (isset($content['language'])): ?>
                <span class="language"><?php echo $this->translate(sprintf('(%s)', $content['language'])); ?></span>
                <?php endif; ?>
            </div>
            <div class='notice-description'><?php echo $notice['text']; ?></div>
        </div>
<?php if (isset($projectUrl)): ?>
</a>
<?php else: ?>
</div>
<?php endif; ?>