<div class="local-contexts-notice">
    <?php if ($notice['image_url'] !== ''): ?>
    <img class='image' src='<?php echo $notice['image_url']; ?>' alt=''>
    <?php endif; ?>
    <div class='local-context-notice-meta'>
        <div class='notice-name'>
            <?php echo $notice['name']; ?>
            <?php if (isset($content['language'])): ?>
            <span class="language"><?php echo $this->translate(sprintf('(%s)', $content['language'])); ?></span>
            <?php endif; ?>
        </div>
        <div class='notice-description'><?php echo $notice['text']; ?></div>
    </div>
</div>