<div class='local-contexts-project'>
<?php if (isset($project['project_url'])): ?>
    <a class="project-name" target="_blank" href="<?php echo($notice_content['project_url']); ?>"><?php echo($project['project_title']); ?></a>
<?php endif; ?>
<?php foreach ($project as $key => $notice): ?>    
    <?php if (is_int($key)): ?>
        <?php echo $this->partial('local-contexts/common/notice.phtml', ['notice' => $notice]); ?>  
    <?php endif; ?>
<?php endforeach; ?>
</div>