<?php
$form->prepare();
$this->htmlElement('body')->appendAttribute('class', 'no-section-hashes');
$escapeHtml = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/local-contexts.css', 'LocalContexts'));
?>

<?php echo $this->pageTitle($this->translate('Assign Notices & Labels'), 1, $this->translate('Local Contexts')); ?>

<nav class="section-nav">
    <ul>
        <li class="active"><a href="#assign"><?php echo $this->translate('Assign'); ?></a></li>
        <li><a href="#notices"><?php echo $this->translate('Notices'); ?></a></li>
    </ul>
</nav>
<?php echo $this->form()->openTag($form); ?>
<fieldset id="assign" class="section active">
    <?php echo $this->formCollection($form, false); ?>
</fieldset>

<fieldset id="notices" class="section">
    <div class="labels">
        <?php foreach($lc_content as $content): ?>
        <div class="label">
            <div class="column check">
                <input name="lc-notice[]" type="checkbox" value="<?php echo $this->escapeHtml(json_encode($content)); ?>">
            </div>
            <img class="column image" src="<?php echo($content['image_url']); ?>">
            <div class="column text">
                <div class="name">
                    <?php 
                    echo($content['name']);
                    if (isset($content['language'])) {
                        echo '<span class="language"> (' . $content['language'] . ')</span>';
                    }
                    ?></div>
                <div class="description"><?php echo $content['text']; ?></div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</fieldset>
<div id="page-actions">
    <button id='index-submit'><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>
<?php echo $this->form()->closeTag($form); ?>
