<script>
$(document).ready( function() {
    <?php 
    $html = '';
    $html .= "<div class='labels'>";
    foreach ($this->contentArray as $content) {
        $html .= "<div class='labels'>";
        $html .= "<img class='column image' src='" . $content['image_url'] . "'>";
        $html .= "<div class='column text'><div class='name'>" . $content['name'] . "</div>";
        $html .= "<div class='description'>" . $content['text'] . "</div></div></div>"; 
    } 
    $html .= "</div>";  
    ?>
    $('footer').prepend("<?php echo $html ?>");
});
</script>
